apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  tls:
  - hosts:
    - demo.imsny.world
    secretName: sslcerts-web
  rules:
  - host: demo.imsny.world
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port: 
              number: 80
