apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: "nginx-api"
          image: imsny/demo-project:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
